arm:
  poses:
    zero:
     joint1: 0.0
     joint2: 0.0
     joint3: 0.0
     joint4: 0.0
     joint5: 0.0
    home:
     joint1: 0.0
     joint2: 0.7854
     joint3: -1.5708
     joint4: -1.5708
     joint5: 0.0
gripper:
  poses:
    close:
     joint1: 0.0
    open:
     joint1: -1.54
